package com.scb.mobilephone.extensions


const val MOBILE_LIST = "MOBILE_LIST"
const val RECEIVED_NEW_MESSAGE = "RECEIVED_NEW_MESSAGE"
const val RECEIVED_FAVORITE = "RECEIVED_FAVORITE"
const val RECEIVED_NEW_FAVORITE_LIST = "RECEIVED_NEW_FAVORITE_LIST"
const val RECEIVED_NEW_FAVORITE = "RECEIVED_NEW_FAVORITE"

// SQLite Database
const val DATABASE_NAME = "FAVORITE_MOBILE"
const val THREAD_NAME = "FAVORITE_THREAD"
const val TABLE_NAME = "FAVORITE_LISTS"
